<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Close</name>
   <tag></tag>
   <elementGuidId>7a8907d5-2149-41e2-a3aa-361b752f2c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Close')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe7677b6-9bce-46f7-93f6-1f00361fa10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Operator/Procurement/ActivePO</value>
      <webElementGuid>688a18f3-37e6-4e63-bd31-5bb9d10d0068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>d84658b4-33d5-474a-96fb-27782c8d8a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>3cca4294-3164-4dde-a777-ecfd121b2132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/div[@class=&quot;az-content pd-y-20 pd-lg-y-30 pd-xl-y-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;az-content-body d-flex flex-column&quot;]/div[@class=&quot;mg-t-20 fixed-footer container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 text-sm-right&quot;]/a[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>5ab4f545-7110-4930-ae6b-3acf03b9862b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Close')]</value>
      <webElementGuid>e2fb109b-a8c0-43b2-b278-233908a0c34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change History'])[1]/following::a[1]</value>
      <webElementGuid>e67bd0b0-41a1-4a5c-8eff-e91d8dfd723a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel PO'])[1]/preceding::a[1]</value>
      <webElementGuid>7408d2ab-6b31-4174-9592-bb97d549c4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change History'])[2]/preceding::a[1]</value>
      <webElementGuid>3f85195e-f57d-474a-bd09-711cf66dd177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Operator/Procurement/ActivePO')])[3]</value>
      <webElementGuid>13c4fce0-5f5f-4adb-97ca-b7d3611d3852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/a</value>
      <webElementGuid>a2f4458d-1440-4d61-a786-b11182cab6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Operator/Procurement/ActivePO' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>ef2adeeb-9077-48a6-94d9-86327ebca607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
