<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CK 1 Vendor_addProduct-Ingredient-21_e5f3ae</name>
   <tag></tag>
   <elementGuidId>f71acf2e-df07-431f-a67b-dcc1fa6227db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addProduct-Ingredient-21028-43721</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addProduct-Ingredient-21028-43721']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84b2680a-22a8-451a-8739-359491c97f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea04b641-5c46-46a2-8ed2-1b96ef9c353c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addProduct-Ingredient-21028-43721</value>
      <webElementGuid>2e32d62f-ff1c-41ab-97f5-81516a347397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>price</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>31720421-a557-4933-acf5-179b18e9a05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ingredient-id</name>
      <type>Main</type>
      <value>21028</value>
      <webElementGuid>c737232e-63f9-4b7a-9d22-e9f45e829682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>promotion-detail-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93c3d628-61de-4971-a61d-2c845baa9e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary addProduct</value>
      <webElementGuid>eefc86e9-2e2e-429b-90b8-25bab5226bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addProduct-Ingredient-21028-43721&quot;)</value>
      <webElementGuid>c3528672-1f07-4247-b345-7229cf67a876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addProduct-Ingredient-21028-43721']</value>
      <webElementGuid>84b20900-6df7-4297-abe4-050885052614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-products']/tbody/tr/td[9]/button</value>
      <webElementGuid>d7a73282-91a5-4e93-80d4-4a979ba3b24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CK 1 Vendor'])[2]/following::button[1]</value>
      <webElementGuid>9db0ae51-926f-4279-9133-b90d2d055444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B2B MULTIPLE PMS TEST'])[1]/following::button[1]</value>
      <webElementGuid>c1e30856-6f73-4287-94b2-f02657907b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anchor Beer BTL'])[1]/preceding::button[1]</value>
      <webElementGuid>27a97b8c-9ee5-480b-bb9c-0892285edb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/button</value>
      <webElementGuid>910faf11-83bd-4609-aefd-96b96ba9635a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addProduct-Ingredient-21028-43721']</value>
      <webElementGuid>4aa3cecc-91a1-4083-8d90-053136f2be50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
