<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CK 1 Vendor_quantity-Ingredient-21028-43721</name>
   <tag></tag>
   <elementGuidId>1237bb47-3ce2-45ff-9e26-57eeb9a2ba7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity-Ingredient-21028-43721</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity-Ingredient-21028-43721']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b342ef5a-acaa-48b4-8b85-291a847a20ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>488ec073-b1ab-459a-b71d-8f8b39e9307c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity-Ingredient-21028-43721</value>
      <webElementGuid>b3a0bc56-70a8-440a-92c9-d742451e8802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>price</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b0b5c0bf-3837-4e55-a768-9fe04af3289e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>abba4a57-3bc2-4ea2-bd82-c45762c91c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quantity form-control float-right text-right</value>
      <webElementGuid>423b495a-690b-44aa-a7ba-1809e027d551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95e0b287-8ea1-438a-9794-a184158db469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity-Ingredient-21028-43721&quot;)</value>
      <webElementGuid>d95e054d-3b5f-4959-a33e-cfc033be0308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity-Ingredient-21028-43721']</value>
      <webElementGuid>a140101e-12b4-40f2-a05b-9b92b6fcc04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-products']/tbody/tr/td[7]/input</value>
      <webElementGuid>e04dba95-c315-4aab-b0be-1ce93903fe53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>dbf8a135-731a-4865-89b8-d58d79f67a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity-Ingredient-21028-43721']</value>
      <webElementGuid>74a3bf14-f9f9-45ed-818f-69663ac9f652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
