<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Date</name>
   <tag></tag>
   <elementGuidId>d76a1a6d-acb4-4acb-b13e-691affaa913a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbl-request_wrapper']/div[2]/div/div/table/thead/tr/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.text-left.sorting_asc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>fcd4c646-fa96-41ac-8574-d3c3f57e68a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left sorting_asc</value>
      <webElementGuid>0f50b86b-5ff4-4906-b9c7-06a31e19ed76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ca06800-e6be-46bf-a9cc-5b5295e43c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tbl-request</value>
      <webElementGuid>717c0863-96bf-471c-8ace-1d0e5b55a3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4dd5f256-3301-4d12-8bd5-69c898acc972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7372821b-1c05-480b-9323-0273c2498215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>ascending</value>
      <webElementGuid>c8a9ad1d-90dc-4f4f-ac6f-6bde87dc78ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date: activate to sort column descending</value>
      <webElementGuid>43861d53-09e2-4419-979b-757c2db3fb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date</value>
      <webElementGuid>eab5af4a-9244-4252-bdc5-414b07568a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-request_wrapper&quot;)/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]/div[@class=&quot;dataTables_scrollHeadInner&quot;]/table[@class=&quot;table table-hover table-striped dataTable no-footer&quot;]/thead[1]/tr[1]/th[@class=&quot;text-left sorting_asc&quot;]</value>
      <webElementGuid>21ebcadd-2d19-4d5d-914e-e088bc1c644a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbl-request_wrapper']/div[2]/div/div/table/thead/tr/th</value>
      <webElementGuid>e5098a07-f3b6-4544-bf2c-2b95ba5a4e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[1]/following::th[1]</value>
      <webElementGuid>af920dd6-9f8d-40f2-82db-5be663210625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Request'])[1]/following::th[1]</value>
      <webElementGuid>ceffa13c-e2f1-48ba-a816-8293494a5b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO Number'])[1]/preceding::th[1]</value>
      <webElementGuid>331ba181-edb8-40b6-b544-ae5ec9969e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet'])[3]/preceding::th[2]</value>
      <webElementGuid>3fabdfad-76c9-47d1-92c3-06018ace59c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Date']/parent::*</value>
      <webElementGuid>6d1bb6be-0f46-4dfd-be2b-7fd7f5d86ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>c6faa4af-5fda-4478-98c4-2b290c4b4439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Date' or . = 'Date')]</value>
      <webElementGuid>73f939e9-d1e9-4f41-ac94-c73f7602d030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
